# Generated by Django 2.0 on 2018-08-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('surname', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeName', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('dishName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Family')),
                ('favorites', models.ManyToManyField(to='thyme.FoodUser')),
            ],
        ),
        migrations.CreateModel(
            name='Timepoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('story', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thyme.FoodUser')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thyme.Recipe')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Timeline')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
