# Generated by Django 2.0 on 2018-08-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookTime',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='prepTime',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
