# Generated by Django 2.0 on 2018-08-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thyme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
